name: wickedelfchild.com
favicon: null
layout_spectrum: 0.3930504391901195
typography_spectrum: 0.29683
title: In My Head
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbaaec'
    - '#180902'
    - '#feffff'
    - '#306f9a'
    - '#a42d31'
  brandStrength: 0.9986078073270619
  lightness: 0.8455386471468955
  saturation: 0.27579381968826056
  rhythmicContrast: 0.6786097730509937
purpose: []
