layout_spectrum: 0.60442
typography_spectrum: 0.36249795765616
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.6833210468757898
  lightness: 0.34294344671070576
  saturation: 0.41934895724989474
  rhythmicContrast: 0.831355819478631
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9a20ca4-e646-4f50-b2a0-6f36b5bdf347.jpg
name: wickedelfchild.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Publisher
    url: 'http://fantasyworkspublishing.com/anne-stinnett.html'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/11729a10-859a-4709-8c4f-bf7454a4211e.jpg
title: In My Head
purpose: []
