typography_spectrum: 0.29683
color:
  brandColors:
    - '#fbaaec'
    - '#180902'
    - '#feffff'
    - '#306f9a'
    - '#a42d31'
  brandStrength: 0.9986078073270619
  lightness: 0.8455386471468955
  saturation: 0.27579381968826056
  rhythmicContrast: 0.6786097730509937
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60442
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f9a20ca4-e646-4f50-b2a0-6f36b5bdf347.jpg
name: wickedelfchild.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Publisher
    url: 'http://fantasyworkspublishing.com/anne-stinnett.html'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/11729a10-859a-4709-8c4f-bf7454a4211e.jpg
title: In My Head
purpose: []
